### ISSUE TITLE
Enable Blargg NTSC Filter cause half of image to shift out of screen

### ISSUE THREAD

**Issue by Great-Dragon** [libretro/nestopia#13] opened 2015-07-08 15:36 UTC
Doesn't matter what type of Blargg filter to choose. The result will be the same.

![retroarch-0708-182748](https://cloud.githubusercontent.com/assets/12208533/8574547/edcc5134-259f-11e5-95b7-25f9c1d65cea.png)

**Comment by hizzlekizzle** [comment] 2015-07-08 15:46
This seems to be caused by the 'mask vertical overscan' core option. Blargg's NTSC filter is extremely resolution-dependent, so this isn't a huge surprise, though it's obviously not intended or optimal.

**Comment by Great-Dragon** [comment] 2015-07-08 15:52
Oh, thanks for that. I've turned it off and it fixes the issue.

How this overscan feature correlated with RetroArch "crop overscan" ?

**Comment by hizzlekizzle** [comment] 2015-07-08 15:55
RA's option is going away eventually and will be replaced by core options either like this one or like mednafen's first/last scanline option, etc. It had to be moved to the cores because it's so weird and inconsistent of a behavior (sometimes varying on a per-game basis) that it didn't make sense for the frontend to be handling it anymore.

**Comment by Great-Dragon** [comment] 2015-07-08 16:13
OK, anyway isn't it's better to change the flow how this Blargg's filter is applied?
I mean it's better to first apply the filter and then crop an image with overscan. But it looks like current flow is otherwise: crop image then apply filter.

**Comment by rdanbrook** [comment] 2015-07-19 01:31
This is now fixed upstream.

**Closed** 2015-07-30 14:20 UTC
