### ISSUE TITLE
Getting the Zapper working on RPI3

### ISSUE THREAD

**Issue by ghost** [libretro/nestopia#49] opened 2017-02-06 00:57 UTC
I'm trying to get the Zapper to work on the Raspberry Pi 3 lr-nestopia under RetroPie. I've got it working now in some other cores (lr-genesis-plus-gx and lr-snes9x2010) this last week by doing a few source modifications.  I do want to say first and foremost that I love nestopia it's my NES emulator of choice and the source for the core and APIs is very clean it hasn't been that hard mostly to pick up on (in a week's time no less), many kudos and thanks to the devs for this wonderful emulator.

The RetroArch rgui menu in-game only shows support for RetroPad and RetroPad w/ Analog.
I got the cursor working in Duck Hunt by uncommenting this line for the Zapper in libretro.cpp that plugs it into the Player 2 slot:

https://github.com/libretro/nestopia/blob/master/libretro/libretro.cpp#L1072

It still isn't registering trigger fires though. I put in some logging around this line to see if it's actually registering zapper.fire = 1 and it is, in fact, it's working all the way up to emulator.Execute(video, audio, input); and retaining zapper.fire == 1 afterward.

For reference:
https://github.com/libretro/nestopia/blob/master/libretro/libretro.cpp#L451

However, it's not doing anything, so maybe something's going on downstream in the emulator execution, but I'm at a stumping point in knowledge of being able to trace/debug further due to the nature of the logging mechanisms in RetroArch having a scope that only goes down as far as libretro goes. 

Also note: I can't test standalone on LXDE because it says "SDL not configured with OpenGL/GLX support" and I think on the Pi 3 I have to use GL/DispmanX drivers that work with RetroArch.  So I'm running through RetroPie/EmulationStation which is my preferred running environment.

Since log_cb is only in scope to libretro, what's the best way to log (or even better produce on-screen messages for debugging) to debug what's going on with the Zapper during emulation?

**Comment by c0d3h4x0r** [comment] 2019-05-13 01:25
I'm also experiencing this with RetroPie on my Pi 3B+.  The on-screen mouse cursor works fine, but neither of the mouse buttons cause the light zapper to fire, so games are unplayable.  Someone please fix this!

**Comment by rdanbrook** [comment] 2019-05-15 14:40
This sounds like a frontend issue, honestly. I can't confirm that because I don't have a Pi 3B+. Does mouse input work as it should in other cores that accept mouse input? Let's try to narrow down the problem. If it is in the Nestopia core, then that will at least give me some indications as to how to fix it.

Also you need NstDatabase.xml to autodetect games that work with the Zapper. If you are missing that file, then indeed you will need to force connect a Zapper into port 2.

**Comment by orbea** [comment] 2019-05-15 15:40
This broke in RetroArch, I'll bisect, but I would suggest making a issue for RetroArch.

**Comment by orbea** [comment] 2019-05-15 15:52
Bisect results.
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
cbfdd7bbd95456958baca345cc198b2664108977
3dc35344983421ef8b6cc190a493a41373c41869
6f116b2edfc841643f42b136c320fca8dde62476
4e79ef9f61eb872d96a8d67d03478df14037baba
c453675d386606871a32fb04af7b1ea3822ebc93
c76545bf6ce87e3b131cf0e406655b1918b5c9de
We cannot bisect more!
```
https://github.com/libretro/RetroArch/commit/cbfdd7bbd95456958baca345cc198b2664108977
https://github.com/libretro/RetroArch/commit/3dc35344983421ef8b6cc190a493a41373c41869
https://github.com/libretro/RetroArch/commit/6f116b2edfc841643f42b136c320fca8dde62476
https://github.com/libretro/RetroArch/commit/4e79ef9f61eb872d96a8d67d03478df14037baba
https://github.com/libretro/RetroArch/commit/c453675d386606871a32fb04af7b1ea3822ebc93
https://github.com/libretro/RetroArch/commit/c76545bf6ce87e3b131cf0e406655b1918b5c9de

**Comment by c0d3h4x0r** [comment] 2019-05-15 16:18
I doubt it’s a retroarch bug because it does not occur in the fce core, only with the nestopia core.

**Comment by orbea** [comment] 2019-05-15 16:23
It was clearly broken in RetroArch, not in nestopia.

There are also issues with runahead that started in PR https://github.com/libretro/RetroArch/pull/7134.

**Comment by rdanbrook** [comment] 2019-05-15 16:32
It certainly does not work in FCEU for me.

**Comment by c0d3h4x0r** [comment] 2019-05-15 17:02
It does for me, after locally applying the relevant mouse-indexing patch to the 1.7.6 version of RetroArch (already fixed in RetroArch mainline) used by RetroPie and locally building and manually copying over the resulting retroarch executable.

**Comment by rdanbrook** [comment] 2019-05-15 17:12
Okay, so we're comparing apples to oranges here then. Do you have more information on this patch? I'd like to see it so I can get a greater understanding of what the problem may be, and maybe double check that it truly is fixed in mainline RA.

**Comment by c0d3h4x0r** [comment] 2019-05-15 18:06
https://retropie.org.uk/forum/topic/16926/retroarch-cores-crash-on-trigger-press-mouse-click-with-overlay-active/29

**Comment by cmitu** [comment] 2019-05-15 19:02
> Okay, so we're comparing apples to oranges here then. Do you have more information on this patch? I'd like to see it so I can get a greater understanding of what the problem may be, and maybe double check that it truly is fixed in mainline RA.

The patch is [here](https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/emulators/retroarch/03_disable_udev_sort.diff), but I'm not sure it affects the issue at hand, since it just removes the sorting of joypads internally by RA.

AFAIK, there was a patch submitted a while ago when someone complained (in the Retropie forums)  about mouse not working in Nestopia as a Zapper - see https://github.com/libretro/RetroArch/pull/773 - but it only occurred when user used a multi-event device from what I could tell (i.e. keyboard/mouse combo).

**Comment by rdanbrook** [comment] 2019-05-15 19:03
Thanks for that link.

The lightgun input in Snes9x is also broken. The issue is now at the RetroArch level, so I am going to close this issue and it will be resolved at the top layer.

**Closed by rdanbrook** 2019-05-15 19:03 UTC
